 rm(list=ls())
library(Hmisc)
data <- read.csv("C:/Users/acer/Downloads/covid_19_data.csv")
View(covid_19_data)
describe(data)
rm(list=ls())
library(Hmisc)
covid_19_data <- read.csv("C:/Users/acer/Downloads/covid_19_data.csv")
View(covid_19_data)
source('C:/Users/acer/covid r.R')
rm(list=ls())
install.packages(Hmisc)
install.packages("Hmisc")
install.packages("dplyr")
library(dplyr)
data <- read.csv("C:/Users/acer/Downloads/covid_19_data.csv")
install.packages("dplyr")
library(dplyr)
data <- read.csv("C:/Users/acer/Downloads/covid_19_data.csv")
data
head(data)
tail(data)
dim(data)
names(data)
glimps(data)
glimpse(data)
glimpse(data)
install.packages("dplyr")
install.packages("dplyr")
library(dplyr)
data$Country.Region
unique(data$Country.Region)
length(unique(data$Country.Region))
mean(data$Confirmed)
meadian(data$Confirmed)
median(data$Confirmed)
range(data$Confirmed)
source('C:/Users/acer/covid r.R')
install.packages("dplyr")
source('C:/Users/acer/covid r.R')
summary(example)
summary(data)
install.packages("dplyr")
library(dplyr)
data <- read.csv("C:/Users/acer/Downloads/covid_19_data.csv")
data<- tbl_df(data)
data
head(data)
tail(data)
dim(data)
names(data)
data$Country.Region
unique(data$Country.Region)
length(unique(data$Country.Region))
mean(data$Confirmed)
median(data$Confirmed)
range(data$Confirmed)
summary(data)
install.packages("dplyr")
library(dplyr)
data <- read.csv("C:/Users/acer/Downloads/covid_19_data.csv")
data<- tbl_df(data)
data
head(data)
tail(data)
dim(data)
names(data)
data$Country.Region
unique(data$Country.Region)
length(unique(data$Country.Region))
mean(data$Confirmed)
median(data$Confirmed)
range(data$Confirmed)
summary(data)
mean(data$Deaths, na.rm= TRUE) 
is.na(data$Deaths) # if True is there their are still null values
sum(is.na(data$Deaths)) # tells the total number of num values present
data[is.na(data)]<- 0 # replace NA to 0
View(data)
library(ggplot2)
ggplot(data,aes(Recovered)) + geom_histogram(bins=20)
ggplot(data,aes(Deaths)) + geom_histogram(bins=80)
ggplot(data,aes(Deaths, Recovered, col=Confirmed)) + geom_point()
ggplot(data,aes(Province.State, Country.Region, col= Last.Update)) + gemo_point()

data<-filter(data,Confirmed>=5500000)
View(data)
t.test(Recovered~Deaths,data=data)
t.test(Deaths~Recovered,data=data)

fit<- lm(Confirmed~Deaths, data= data) 
summary(fit)
library(ggplot2)
ggplot(data, aes(x=Confirmed,y=Deaths)) + gemo_point() + gemo_smooth(methord="lm")

